### ISSUE TITLE
Version 2.7.0 - gives updating fail message with apple news

### ISSUE THREAD

**Issue by adept-li-fire** [10up/brightcove-video-connect#287]
### Describe the bug

Hi there, 

We started getting reports of the message "updating failed" when trying to update a post on two WP installs that are hosted on WPE. This started happening right after we applied the update 2.7.0. 

Below is the output that was in the error log right after the issue would happen. We rolled back to 2.6.1 and are able to update post just as before. 

Error log: 

{
  "installName": "mysite",
  "environment": "PROD",
  "type": "error",
  "date": "2022-08-11T18:58:12.000Z",
  "severity": "error",
  "client": "user-IP-address:0",
  "message": "PHP Fatal error:  Uncaught Error: Class 'BC_CMS_API' not found in /nas/content/live/mysite/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-export.php:561\

  \nStack trace:\

  \n#0 /nas/content/live/mysite/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-export.php(491): Apple_Actions\\\\Index\\\\Export->get_brightcove_stillurl('xxxxxxxx', 'xxxxxxxx')\

  \n#1 /nas/content/live/mysite/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-export.php(598): Apple_Actions\\\\Index\\\\Export->format_brightcove('<!-- wp:bc/brig...')\

  \n#2 /nas/content/live/mysite/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-export.php(172): Apple_Actions\\\\Index\\\\Export->get_content(Object(WP_Post))\

  \n#3 /nas/content/live/mysite/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-push.php(559): Apple_Actions\\\\Index\\\\Export->fetch_exporter()\

  \n#4 /nas/content/live/mysite/wp-content/plugins/publish-to-apple-news/admin/a in /nas/content/live/mysite/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-export.php on line 561, referer: https://nbc-2.com/wp-admin/post.php?post=xxxxxxxx&action=edit",
  "uuid": "d6f21b2a-112b-4b36-b865-5e3500a853cc"
}

I'm you are aware of this [issue](https://github.com/alleyinteractive/apple-news/issues/942) on the Apple News plugin repo, but I thought it would be nice to include it. 

### Steps to Reproduce

1. Update to 2.7.0 from 2.6.1
2. Try to update a post and will receive "Updating failed" message

### Screenshots, screen recording, code snippet

![Screen Shot 2022-08-11 at 3 19 31 PM](https://user-images.githubusercontent.com/78180140/184244269-cf1db53a-86cb-459d-8451-432610cba42f.png)

### Environment information

- Mac Mini 
- Chrome Version 104.0.5112.79

### wp-core ###

version: 6.0.1
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%category%/%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 78
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /nas/content/live/mysite
wordpress_size: loading...
uploads_path: /nas/content/live/mysite/wp-content/uploads
uploads_size: loading...
themes_path: /nas/content/live/mysite/wp-content/themes
themes_size: loading...
plugins_path: /nas/content/live/mysite/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: JNews - Child Theme (jnews-child)
version: 1.0.0
author: Jegtheme
author_website: http://themeforest.net/user/jegtheme?ref=jegtheme
parent_theme: JNews (jnews)
theme_features: core-block-patterns, widgets-block-editor, menus, automatic-feed-links, title-tag, post-thumbnails, align-wide, customize-selective-refresh-widgets, post-formats, html5, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, auto-load-next-post, editor-styles, editor-style, widgets
theme_path: /nas/content/live/mysite/wp-content/themes/jnews-child
auto_update: Disabled

### wp-parent-theme ###

name: JNews (jnews)
version: 10.7.8
author: Jegtheme
author_website: http://jegtheme.com/
theme_path: /nas/content/live/mysite/wp-content/themes/jnews
auto_update: Disabled

### wp-themes-inactive (2) ###

Twenty Twenty-One: version: 1.6, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.2, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (8) ###

Elementor Safe Mode: version: 1.0.0, author: Elementor.com
Force Strong Passwords - WPE Edition: version: 1.8.0, author: Jason Cosper
MU WP Native PHP Sessions: version: 0.1, author: Pantheon
WPE ElasticPress Autosuggest Logger: version: 1.0.0, author: WP Engine
WP Engine Cache Plugin: version: 1.0.10, author: WP Engine
WP Engine Seamless Login Plugin: version: 1.6.0, author: WP Engine
WP Engine Security Auditor: version: 1.0.10, author: wpengine
WP Engine System: version: 5.0.1, author: WP Engine

### wp-plugins-active (49) ###

AAM Complete Package: version: 5.2.13, author: Vasyl Martyniuk <vasyl@vasyltech.com>, Auto-updates disabled
ACF Options Page Admin: version: 3.10.0, author: John A. Huebner II, Auto-updates disabled
Add Categories to Pages.: version: 1.2, author: a.ankit, Auto-updates disabled
Ad Inserter Pro: version: 2.7.17, author: Ad Inserter Pro, Auto-updates disabled
Ads.txt Manager: version: 1.4.0, author: 10up, Auto-updates disabled
Advanced Access Manager: version: 6.8.4, author: Vasyl Martyniuk <vasyl@vasyltech.com>, Auto-updates disabled
Advanced Custom Fields PRO: version: 5.12.3, author: Delicious Brains, Auto-updates disabled
AMP: version: 2.3.0, author: AMP Project Contributors, Auto-updates disabled
AMP Mobile Server-Side Redirection: version: 0.1, author: Weston Ruter, Google, Auto-updates disabled
Better Search Replace: version: 1.4.1, author: Delicious Brains, Auto-updates disabled
Brightcove Video Connect: version: 2.6.1, author: 10up (latest version: 2.7.0), Auto-updates disabled
Chartbeat: version: 2.0.7, author: Chartbeat, Auto-updates disabled
Custom Facebook Feed Pro Smash: version: 4.2.3, author: Smash Balloon, Auto-updates disabled
Custom Simple Rss: version: 2.1.3, author: Danny(Danikoo) Haggag, Auto-updates disabled
Custom Twitter Feeds Pro Developer: version: 1.14.2, author: Smash Balloon, Auto-updates disabled
Default featured image: version: 1.7.2.1, author: Jan Willem Oostendorp, Auto-updates disabled
Distributor: version: 1.7.1, author: 10up Inc., Auto-updates disabled
Duplicate Page: version: 4.4.9, author: mndpsingh287, Auto-updates disabled
Elementor: version: 3.6.8, author: Elementor.com (latest version: 3.7.0), Auto-updates disabled
Elementor Pro: version: 3.7.3, author: Elementor.com, Auto-updates disabled
Favicon by RealFaviconGenerator: version: 1.3.25, author: Philippe Bernard, Auto-updates disabled
GDPR Cookie Consent: version: 2.1.2, author: WebToffee, Auto-updates disabled
GutenBee: version: 2.15.0, author: The CSSIgniter Team, Auto-updates disabled
Instagram Feed Pro Developer: version: 6.0.4, author: Smash Balloon, Auto-updates disabled
Jetpack: version: 11.2, author: Automattic, Auto-updates disabled
JNews - AMP Extender: version: 10.0.3, author: Jegtheme, Auto-updates disabled
JNews - Breadcrumb: version: 10.0.1, author: Jegtheme, Auto-updates disabled
JNews - Essential: version: 10.0.7, author: Jegtheme, Auto-updates disabled
JNews - JSON-LD: version: 10.0.2, author: Jegtheme, Auto-updates disabled
JNews - Meta Header: version: 10.0.2, author: Jegtheme, Auto-updates disabled
ManageWP - Worker: version: 4.9.14, author: GoDaddy, Auto-updates disabled
oEmbed Plus: version: 1.6, author: Ayesh Karunaratne, Auto-updates disabled
One Click Accessibility: version: 2.0.3, author: One Click Accessibility, Auto-updates disabled
Publish to Apple News: version: 2.3.2, author: Alley, Auto-updates disabled
ReOrder Posts within Categories: version: 2.10.2, author: Aurorata V. (latest version: 2.12.5), Auto-updates disabled
Reset Meta Box Positions: version: 0.1.2, author: David Gwyer, Auto-updates disabled
Site Kit by Google: version: 1.80.0, author: Google, Auto-updates disabled
TotalPoll – Pro: version: 4.8.4, author: TotalSuite, Auto-updates disabled
Vafpress Post Formats UI: version: 1.5.3, author: vafpress, Auto-updates disabled
WP All Import Pro: version: 4.7.5, author: Soflyy (latest version: 4.7.6), Auto-updates disabled
WPCode - Insert Headers, Footers, and Code Snippets: version: 2.0.1, author: WPCode, Auto-updates disabled
WP Engine Advanced Cache Options: version: 1.3.3, author: Ethan Kennedy, Steven Word, Auto-updates disabled
WPForms: version: 1.7.5.5, author: WPForms, Auto-updates disabled
WP Native Articles Premium: version: 1.5.3, author: OzTheGreat (WPArtisan), Auto-updates disabled
WP Rocket: version: 3.11.5, author: WP Media, Auto-updates disabled
Wufoo Shortcode Plugin: version: 1.46, author: Wufoo, Auto-updates disabled
Yoast SEO: version: 19.4, author: Team Yoast (latest version: 19.5.1), Auto-updates disabled
Yoast SEO: News: version: 13.1, author: Team Yoast, Auto-updates disabled
Yoast SEO Premium: version: 19.0.1, author: Team Yoast (latest version: 19.1), Auto-updates disabled

### wp-plugins-inactive (12) ###

Advanced Custom Fields: version: 5.12.3, author: Delicious Brains, Auto-updates disabled
JNews - Auto Load Next Post: version: 10.0.3, author: Jegtheme, Auto-updates disabled
JNews - Gallery: version: 10.0.2, author: Jegtheme, Auto-updates disabled
JNews - Gutenberg: version: 10.0.1, author: Jegtheme, Auto-updates disabled
JNews - Instagram Feed: version: 10.0.0, author: Jegtheme, Auto-updates disabled
JNews - Social Login: version: 10.0.3, author: Jegtheme, Auto-updates disabled
JNews - Social Share: version: 10.0.5, author: Jegtheme, Auto-updates disabled
JNews - Video: version: 10.0.6, author: Jegtheme, Auto-updates disabled
JNews - View Counter: version: 10.0.5, author: Jegtheme, Auto-updates disabled
JNews - Weather: version: 10.0.3, author: Jegtheme, Auto-updates disabled
PublishPress Future: version: 2.7.7, author: PublishPress, Auto-updates disabled
WP 404 Auto Redirect to Similar Post: version: 1.0.3, author: hwk-fr, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 100M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 137 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.188+ x86_64
httpd_software: nginx
php_version: 7.4.28 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 60
memory_limit: 512M
max_input_time: 10
upload_max_filesize: 50M
php_post_max_size: 100M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.38-41-log
client_version: mysqlnd 7.4.28
max_allowed_packet: 16777216
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /nas/content/live/mysite/wp-content
WP_PLUGIN_DIR: /nas/content/live/mysite/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 208760596
ssl_cert: No
time_diff: undefined
version_option: 11.2:1659642569
old_version: 11.1:1657237627
public: Public
master_user: #2 mattb
current_user: #47 alexm
tokens_set: Blog 
blog_token: V6(&bVmE@OKcD)D%nkE)Roximyz4WJWP
user_token: Not set.
version: 11.2
jp_plugin_dir: /nas/content/live/mysite/wp-content/plugins/jetpack/
plan: free
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Wed, 13 Jul 2022 20:10:28 +0000","finished":"Wed, 13 Jul 2022 20:10:37 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"1"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[1],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/abc-7.com","siteurl":"https:\/\/abc-7.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### google-site-kit ###

version: 1.80.0
php_version: 7.4.28
wp_version: 6.0.1
reference_url: https://abc-7.com
amp_mode: secondary
site_status: not-connected
user_status: not authenticated
verification_status: not-verified
connected_user_count: none
active_modules: site-verification, search-console, pagespeed-insights
recoverable_modules: none
required_scopes: 
	openid: ⭕
	https://www.googleapis.com/auth/userinfo.profile: ⭕
	https://www.googleapis.com/auth/userinfo.email: ⭕
	https://www.googleapis.com/auth/siteverification: ⭕
	https://www.googleapis.com/auth/webmasters: ⭕
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ⭕
	googlesitekit_view_dashboard: ⭕
	googlesitekit_manage_options: ⭕
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ⭕
	googlesitekit_view_wp_dashboard_widget: ⭕
	googlesitekit_view_admin_bar_menu: ⭕
enabled_features: 
	adsenseSetupV2: ⭕
	dashboardSharing: ⭕
	ga4ActivationBanner: ⭕
	ideaHubModule: ⭕
	twgModule: ⭕
	userInput: ⭕
	zeroDataStates: ⭕
search_console_property: none

### amp_wp ###

amp_slug_query_var: amp
amp_slug_defined_late: false
amp_mode_enabled: reader
amp_reader_theme: legacy
amp_templates_enabled: post, page
amp_serve_all_templates: This option does not apply to Reader mode.
amp_css_transient_caching_disabled: n/a
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: undefined
amp_css_transient_caching_time_series: 
	20210107: 144
	20210108: 145
	20210109: 145
	20210110: 144
	20210111: 141
	20210112: 144
	20210113: 142
	20210114: 142
	20210115: 145
	20210116: 142
	20210117: 142
	20210118: 144
	20210119: 143
	20210120: 142
amp_libxml_version: 2.9.4

### distributor ###

0: 1.7.1
1: Yes
2: karl@dgt.me
3: 
	Override Author Byline: Yes
	Media Handling: Featured image only
4: N/A
5: 
	NBC-2: 
- URL: https://nbc-2.com/wp-json/
- Version: 1.7.1
- Status: valid
- Auth method: Username / Password
- Username: admin_wbbh
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "wp_block", "jp_pay_order", "jp_pay_product"], "can_get":["post", "page", "attachment", "wp_block", "feedback", "jp_pay_order", "jp_pay_product"], "endpoint_suggestion":false, "is_authenticated":"yes"}
	CNN: 
- URL: https://waterman-feed.adept.li/wp-json
- Version: 1.6.9
- Status: valid
- Auth method: Username / Password
- Username: admin_wbbh
- Roles Allowed to Push: administrator, editor
- Additional data: {"errors":[], "can_post":["post", "page", "attachment", "wp_block"], "can_get":["post", "page", "attachment", "wp_block"], "endpoint_suggestion":false}

### wpforms ###

version: 1.7.5.5
pro: Jul 27, 2020 @ 1:17pm
upload_dir: Writable
db_tables: wp_wpforms_entries, wp_wpforms_entry_fields, wp_wpforms_entry_meta, wp_wpforms_tasks_meta
total_forms: 1
total_entries: undefined
license_status: Valid
license: Elite
license_location: option

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevinfodness** [comment]
That actually looks like it's my issue to fix in Publish to Apple News. Thanks for reporting!
